dist: xenial
language: rust
sudo: false

notifications:
    email:
        on_success: never
        on_failure: change

rust:
  - stable
  - beta
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

os:
  - linux

cache:
  cargo: true
  apt: true

addons:
  apt:
    packages:
      - libgtk-3-dev

before_script:
  - rustup component add clippy || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
  - rustup component add rustfmt
  - (test -x $HOME/.cargo/bin/just || cargo install just)

script:
  - just fmt-check
  - just build
  - just test
  - just build-features-viewer
