dist: xenial
language: rust
sudo: false

notifications:
    email:
        on_success: never
        on_failure: change

rust:
  - stable
  - beta
  - nightly

os:
  - linux

cache:
  cargo: true
  apt: true

addons:
  apt:
    packages:
      - libgtk-3-dev

before_script:
  - rustup component add rustfmt
  - (test -x $HOME/.cargo/bin/just || cargo install just)

script:
  - just fmt-check
  - just build
  - just test
  - just build-features-viewer
