[package]
name = "mapper"
version = "0.1.0"
authors = ["acheronfail <acheronfail@gmail.com>"]
edition = "2018"
build = "../build.rs"

[dependencies]
evdev-rs = { git = "https://github.com/ndesh26/evdev-rs" }
karabinux = { path = "../karabinux" }
libc = "^0.2.36"
structopt = "0.2"
